apiVersion: extensions/v1beta1 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: $APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      securityContext:
        runAsUser: 0
      containers:

      - name: jenkins
        image: mateothegreat/docker-alpine-jenkins-gcloud
        imagePullPolicy: always

        ports:
          - containerPort: 8080
          - containerPort: 50000
          - containerPort: 50001
          
        env:
          - name: GCLOUD_KEY_FILE
            value: $GCLOUD_KEY_FILE
          - name: GCLOUD_PROJECT
            value: $GCLOUD_PROJECT
          - name: GCLOUD_ZONE
            value: $GCLOUD_ZONE

        readinessProbe:
            tcpSocket:
                port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20

        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi

        volumeMounts:
        
          - mountPath: /var/run
            name: docker-sock

          - mountPath: /var/jenkins_home
            name: $PERSISTENT_DISK

          - name: $GCLOUD_SECRET
            mountPath: "/service_account"
            readOnly: true

      volumes:

      - name: docker-sock
        hostPath:
          path: /var/run

      - name: $PERSISTENT_DISK
        persistentVolumeClaim:
          claimName: $PERSISTENT_DISK

      - name: $GCLOUD_SECRET
        secret:
          secretName: $GCLOUD_SECRET
