apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-storage
  labels:
    app: jenkins-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
