---
  kind: Service
  apiVersion: v1
  metadata:
    name: jenkins-ui
  spec:
    type: NodePort
    selector:
      app: jenkins
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        name: ui
      - protocol: TCP
        port: 50000
        targetPort: 50000
        name: slaves
