apiVersion: v1
kind: PersistentVolume
metadata:
  name: $PERSISTENT_DISK
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: $PERSISTENT_DISK