apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $PERSISTENT_DISK
  labels:
    app: $PERSISTENT_DISK
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
