apiVersion: v1
kind: PersistentVolume
metadata:
  name: $PERSISTENT_DISK
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-06b92293a489b558a
    fsType: ext4